name: test github actions

on:
  push:
    tags:
      - "v*"
    branches:
      - main
  pull_request_target:
    branches:
      - main


jobs:
  wheel:
    name: "${{ matrix.build }} ${{ matrix.os }} ${{ matrix.arch }}"
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        arch: ["x86_64", "aarch64"]
        build: ["cp38-*", "cp39-*", "cp310-*", "cp311-*", "cp312-*", "pp38-*", "pp39-*", "pp310-*"]
        exclude:
          - os: "macos-latest"
            arch: "aarch64"
          - arch: "aarch64"
            build: "pp38-*"
          - arch: "aarch64"
            build: "pp39-*"
          - arch: "aarch64"
            build: "pp310-*"
    steps:
      - uses: actions/checkout@v4
      - run: echo run wheel

  sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo run sdist

  release:
    needs: ["wheel", "sdist"]
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
      - run: curl https://github.com/nim65s.gpg | gpg --import
      - run: echo git verify-tag --raw ${{ github.ref_name }}
      - run: git verify-tag --raw ${{ github.ref_name }}
      - run: git verify-tag --raw ${{ github.ref_name }} 2>&1 | tee test
      - run: cat test
      - name: validate signature
        run: >
          git verify-tag --raw ${{ github.ref_name }} 2>&1
          | grep -q 'VALIDSIG 9B1A79065D2F2B806C8A5A1C7D2ACDAF4653CF28'
      - run: echo run release
